blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions & Questions
    url: https://github.com/mian196/ProtoFS/discussions
    about: Ask questions, share ideas, and connect with the community.
