#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

console.log('[android:init] Locating Tauri crate via cargo metadata...');
const metaRaw = execSync('cargo metadata --format-version 1', {
  cwd: rootDir,
  maxBuffer: 50 * 1024 * 1024,
}).toString();
const meta = JSON.parse(metaRaw);
const pkg = meta.packages.find((p) => p.name === 'tauri');
if (!pkg) {
  throw new Error('Could not locate tauri crate in cargo metadata');
}

const tauriMobileAndroid = path.join(path.dirname(pkg.manifest_path), 'mobile', 'android');
console.log(`[android:init] Found Tauri Android SDK at: ${tauriMobileAndroid}`);

const pkgJson = JSON.parse(readFileSync(path.join(rootDir, 'package.json'), 'utf8'));
const version = pkgJson.version || '0.4.2';

const androidGenDir = path.join(rootDir, 'crates', 'protofs-tauri', 'gen', 'android');
const appDir = path.join(androidGenDir, 'app');

if (!existsSync(androidGenDir)) {
  mkdirSync(androidGenDir, { recursive: true });
}
if (!existsSync(appDir)) {
  mkdirSync(appDir, { recursive: true });
}

// 1. tauri.settings.gradle
const escapedDir = tauriMobileAndroid.replace(/\\/g, '\\\\');
const settingsContent = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
include ':tauri-android'
project(':tauri-android').projectDir = new File("${escapedDir}")
`;
writeFileSync(path.join(androidGenDir, 'tauri.settings.gradle'), settingsContent, 'utf8');
console.log('[android:init] Generated crates/protofs-tauri/gen/android/tauri.settings.gradle');

// 2. app/tauri.build.gradle.kts
const buildContent = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
val implementation by configurations
dependencies {
  implementation("androidx.lifecycle:lifecycle-process:2.10.0")
  implementation(project(":tauri-android"))
}
`;
writeFileSync(path.join(appDir, 'tauri.build.gradle.kts'), buildContent, 'utf8');
console.log('[android:init] Generated crates/protofs-tauri/gen/android/app/tauri.build.gradle.kts');

// 3. app/tauri.properties
const propContent = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=${version}
tauri.android.versionCode=1
`;
writeFileSync(path.join(appDir, 'tauri.properties'), propContent, 'utf8');
console.log('[android:init] Generated crates/protofs-tauri/gen/android/app/tauri.properties');

console.log('[android:init] Successfully initialized Android project files.');
